{% set name = "django-enumfields" %}
{% set version = "0.10.1" %}
{% set sha256 = "839fbf620b6a1d9f5ceff4933fbedd606e908d7e5b5a6a81736066bf8efa89f6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hzdg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >1.7
    - enum34  # [py27]

test:
  imports:
    - enumfields

about:
  home: https://github.com/hzdg/django-enumfields
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Real Python Enums for Django
  doc_url: https://github.com/hzdg/django-enumfields/blob/master/README.rst
  dev_url: https://github.com/hzdg/django-enumfields

extra:
  recipe-maintainers:
    - kwilcox
