{% set name = "django-enumfields" %}
{% set version = "2.1.0" %}
{% set sha256 = "37c86214089ee09f375a135ba8e269da7c154fff76c063f5948becd802a33c0a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hzdg/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >1.7
    - enum34  # [py27]

test:
  imports:
    - enumfields

about:
  home: https://github.com/hzdg/django-enumfields
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Real Python Enums for Django
  doc_url: https://github.com/hzdg/django-enumfields/blob/master/README.rst
  dev_url: https://github.com/hzdg/django-enumfields

extra:
  recipe-maintainers:
    - kwilcox
