appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kcoNespwkUiWIeygP25+nigWmdoQjnONihhBpJPpfAIyD+n8LlEjpSnrzBQXtKAWz4rQFIOYZkT/I764wDki3z62o0LYBQETWTzmqHVXTyed59oK8ZaoL1fvHIQSQTf+fhAeqdmoBYGNet9KEKSfSnbKAu6bGJgkb4wcBv/XfoZxK1ujDvYRgsAf2vhkUJyGF1MuPQE5qiDQ8vJ8G7YOt2OYE5m/MlvIYtBdmyhUHerm4eC6n1siN9zzuR+Hl03pGy9Pzl6yGjxe59I64p82mDNVCuPjwwZFvrnCk+h9BrycvFcRZb0Uvl6hXXC0tkRh5xSLhmf3uAgZlxGmU8naM7i9jf67okpSsy5Y1NO7w+IRvIlaO6otQXu4NikfwlF23RnazhTsM2alQQNofIcJ8Hh0jTeB4CgsofggUchpfaW3kWn8mLWNeYERip1M3u2Yr1K6OZtCWM1BvO8OptxzAQHvYDHBVk0YxftqloyyasnCAsWCuUHWiPwomgWnnyJsHSfLDlEvzeG6HHPm/c5Bq+EZp1+TCUTKcpR98qTTupyH4PqQn9zKtSoZVVFWLcleuC3bPz2xhUpjBW5Vk6NZst3hQ6W/uOHfmnReSnPXlf1ceIJsBtevTTUYOL+2u+wYLM0YRXKLsF98PnCd/dC7lAqHWa+yPsg3Kum6HXn6gZk=}
provider:
  win: azure
conda_forge_output_validation: true
